# Generated by Django 5.0 on 2024-11-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('TitleName', models.CharField(max_length=30)),
                ('HasPassport', models.BooleanField(max_length=30)),
                ('Salary', models.IntegerField()),
                ('Birthday', models.DateField()),
                ('HireDate', models.DateField()),
                ('Notes', models.CharField(max_length=30)),
                ('Country', models.CharField(choices=[('IND', 'INDIA'), ('usa', 'United States'), ('Sth', 'RASth'), ('ADB', 'ABADA'), ('Spa', 'Spain'), ('Au', 'Aus')], default=None, max_length=35)),
            ],
        ),
    ]
