# Generated by Django 5.0 on 2024-11-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
