# Generated by Django 5.0 on 2024-11-23 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0003_country_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Country',
        ),
        migrations.AddField(
            model_name='employee',
            name='EmpCountry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Payroll.country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='EmpDepartment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Payroll.department'),
        ),
    ]
