# Generated by Django 5.0 on 2024-11-23 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0005_alter_country_id_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpCountry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='Countries', to='Payroll.country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpDepartment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='Departmens', to='Payroll.department'),
        ),
    ]
